; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
extra_scripts = pre:extra_scripts/os_platform_packages.py
lib_ignore = Servo
lib_deps = 
	adafruit/Adafruit BusIO
	waspinator/AccelStepper@^1.64
	adafruit/Adafruit AS5600 Library@^1.0.0
