#ifndef CAN_CONFIG_H
#define CAN_CONFIG_H

#define DEVICE_NAME "PTM175"
#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 0

#define ADDRESS_FIRMWARE_VERSION 0x600
#define REPLY_FIRMWARE_VERSION 0x601

#define CAN_ID_MAINPOWER 0x10
#define CAN_CMD_MAINPOWER_OFF 0x00
#define CAN_CMD_MAINPOWER_ON 0x01

#define CAN_ID_RUNMOVE_X 0x11
#define CAN_ID_RUNMOVE_Y 0x12

#define CAN_ID_SERVO_TRIGGER 0x13
#define MIN_SERVO_ANGLE 90  // 90 degrees
#define MAX_SERVO_ANGLE 145  // 145

#define CAN_ID_RUNSPEED_XY 0x14
#define CAN_ID_SET_CONFIG_X 0x15
#define CAN_ID_SET_CONFIG_Y 0x16
#define CAN_COM_READ_SPEED 1
#define CAN_COM_READ_ACCEL 2

#define CAN_ID_MOVE_Y_TO_ZERO 0x17
#define HOME_TOLERANCE_DEG 1.0f
#define HOME_SPEED 50.0f



#define CAN_BAUDRATE 500000
#define SPI_MOSI_PIN 8
#define SPI_MISO_PIN 15
#define SPI_SCK_PIN 14
#define SPI_CAN_CS_PIN 19

#define MAIN_POWER_PIN 6

#define SERVO_TRIGGER_PIN 26

#define X_AXIS_STEP_PIN D11
#define X_AXIS_DIR_PIN D10
//#define X_AXIS_ENABLE_PIN

#define Y_AXIS_STEP_PIN D13
#define Y_AXIS_DIR_PIN D12
//#define Y_AXIS_ENABLE_PIN 

#endif // CONFIG_H
