#ifndef CAN_CONFIG_H
#define CAN_CONFIG_H

#define DEVICE_NAME "PTM175"
#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 0

#define ADDRESS_FIRMWARE_VERSION 0x600
#define REPLY_FIRMWARE_VERSION 0x601

#define CAN_ID_PTM 0xC0
#define CAN_CMD_PTM_STOP 0x00     
#define CAN_CMD_PTM_START_FW 0x01     
#define CAN_CMD_PTM_START_REV 0x02

#define CAN_BAUDRATE 500000
#define SPI_MOSI_PIN 8
#define SPI_MISO_PIN 15
#define SPI_SCK_PIN 14
#define SPI_CAN_CS_PIN 19

#define MAIN_POWER_PIN 6

#define SERVO_TRIGGER_PIN 25

#define X_AXIS_STEP_PIN 11
#define X_AXIS_DIR_PIN 10
//#define X_AXIS_ENABLE_PIN

#define Y_AXIS_STEP_PIN 13
#define Y_AXIS_DIR_PIN 12
//#define Y_AXIS_ENABLE_PIN 

#endif // CONFIG_H